language: php

cache:
  directories:
    - $HOME/.composer/cache

sudo: false

branches:
    only:
        - master
        - /^\d+\.\d+$/

matrix:
    include:
        - php: 7.3
          env: EZ_KERNEL_VERSION=^8.0

install:
    - phpenv config-rm xdebug.ini
    - echo 'memory_limit = -1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
    - composer require "ezsystems/ezpublish-kernel:${EZ_KERNEL_VERSION}" --no-update
    - composer install

script:
    - php vendor/bin/phpunit
